name: Continous Integration

on:
  push:
    branches:
      - '**'

jobs:
  lint-and-build:
    name: Lint and typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Restore cached node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Type check
        run: yarn typecheck

      - name: Lint
        run: yarn lint
